version: '4'
services:
  conteneur-loc-mns:
    image: loc-mns-back-end
    build:
      context: .
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - uploaded_files:/uploads

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    ports:
      - "8888:80"

  mysql:
    image: mysql:5
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    external: true
  uploaded_files:
    external: true
